<script lang="ts">
  import { translate as t } from '$lib/stores/language';
  import Asterisk from '$lib/components/Asterisk.svelte';
  import './portfolio.css';
  import Icon from '$lib/components/Icon.svelte';
  import Skills from '$lib/components/Skills.svelte';
  import NewExperiences from '$lib/components/NewExperiences.svelte';
  import { contact, resume } from '$lib/data/config';
  import { reveal, magnetic, projectMotion, parallax, ambientMotion } from '$lib/animations/motion';
</script>
<svelte:head><title>{$t("Johan Aristizabal — Diseño, código & movimiento")}</title></svelte:head>
<div class="portfolio">
  <section class="portfolio-hero" use:ambientMotion>
    <div class="hero-backdrop" aria-hidden="true"></div>
    <div class="hero-topline"><span class="availability"><span></span> {$t("ABIERTO A NUEVAS IDEAS")}</span><span>{$t("INDEPENDENT DESIGNER & DEVELOPER")}</span></div>
    <div class="hero-stage shell">
      <div class="hero-statement"><p class="eyebrow hero-enter">{$t("DISEÑO + CÓDIGO + UN POCO DE CURIOSIDAD")}</p><h1><span class="line-mask"><span>{$t("Diseño que")}</span></span><span class="line-mask"><span>{$t("se")} <em>{$t("siente.")}</em><i><Asterisk /></i></span></span></h1><div class="hero-intro hero-enter"><span class="intro-arrow">↘</span><p>{$t("Transformo ideas en experiencias digitales.")}<br />{$t("Claras, intuitivas y con carácter.")}</p></div><div class="hero-actions"><a class="round-link hero-enter" href="#works" use:magnetic><span>{$t("Explora")}<br />{$t("mi trabajo")}</span><Icon name="arrow" size={22} /></a><a class="resume-link hero-enter" href={resume.url} download={resume.filename} aria-label="{$t("Descargar mi hoja de vida en PDF")}"><Icon name="download" size={16} /><span>{$t("Mi hoja de vida")} <small>PDF</small></span></a></div></div>
      <div class="sculpture-wrap" use:parallax={90}><div class="sculpture" aria-hidden="true"><div class="sculpture-orbit orbit-a"></div><div class="sculpture-orbit orbit-b"></div><div class="sculpture-orbit orbit-c"></div><div class="sculpture-core"><span>j.</span></div><span class="sculpture-satellite satellite-one"></span><span class="sculpture-satellite satellite-two"></span></div><a class="sculpture-caption" href="#works">{$t("EXPLORAR ES PARTE DEL PROCESO")} <i aria-hidden="true">↗</i></a><span class="sculpture-index" aria-hidden="true">{$t("FIG. 001 — SIEMPRE EN MOVIMIENTO")}</span></div>
    </div>
    <div class="name-ticker" aria-hidden="true"><div><span>Johan Aristizabal — </span><span>Johan Aristizabal — </span></div></div>
    <div class="hero-bottomline"><span>{$t("COLOMBIA / DISPONIBLE EN TODO EL MUNDO")}</span><a href="#works">{$t("SCROLL PARA EXPLORAR")} <span>↓</span></a><span>{$t("PORTAFOLIO / 2026")}</span></div>
  </section>
  <section class="portfolio-intro shell" id="about" use:ambientMotion><p class="eyebrow" use:reveal>{$t("01 / UN POCO SOBRE MÍ")}</p><div class="intro-layout"><h2 use:reveal={80}>{$t("Las buenas interfaces")}<br />{$t("no solo se ven bien.")}<br /><span class="serif">{$t("Se sienten bien.")}</span></h2><div class="intro-copy" use:reveal={180}><span class="small-star" aria-hidden="true"><Asterisk /></span><p>{$t("Soy Johan. Me gusta encontrar ese punto donde el diseño, el código y la interacción hacen clic.")}</p><p>{$t("Construyo experiencias que invitan a explorar. Con intención en cada detalle y curiosidad en cada paso.")}</p><a href={contact.whatsappUrl} target="_blank" rel="noreferrer" class="inline-link">{$t("Más sobre tu próxima idea")} <Icon name="arrow" size={18} /></a></div></div><div class="expertise-line" use:reveal><span>{$t("DISEÑO DE INTERFACES")}</span><span>{$t("DESARROLLO FRONTEND")}</span><span>{$t("INTERACCIÓN & MOTION")}</span><span class="expertise-stack">SVELTEKIT / TYPESCRIPT</span></div></section>
  <Skills />
  <section class="portfolio-works shell" id="works"><div class="works-heading" use:reveal><div><p class="eyebrow">{$t("03 / IDEAS EN ACCIÓN")}</p><h2>{$t("Selected")} <span class="serif">{$t("works.")}</span><sup>(04)</sup></h2></div><p>{$t("Hechos para experimentar.")}<br />{$t("No solo para mirar.")}</p></div>
    <a class="showcase focus-showcase" href="/works/focus-flow/" use:reveal use:projectMotion use:ambientMotion><div class="showcase-image"><div class="showcase-grid" aria-hidden="true"></div><div class="showcase-top"><span>FOCUS FLOW®</span><span>{$t("PRODUCTIVIDAD / 01")}</span></div><div class="focus-scene" aria-hidden="true"><div class="scene-sidebar"><span class="scene-brand"><Asterisk /> focus flow</span><span class="scene-menu selected">{$t("◉ Mi espacio")}</span><span class="scene-menu">{$t("◷ Sesiones")}</span><span class="scene-menu">{$t("↗ Mi progreso")}</span><div class="scene-sidebar-bottom">{$t("Encuentra tu ritmo.")}<br /><span>{$t("Una cosa a la vez.")}</span></div></div><div class="scene-content"><div class="scene-welcome"><div><small>{$t("MENOS RUIDO. MÁS ENFOQUE.")}</small><h3>{$t("Hoy es un buen día.")}</h3></div><span><Asterisk /></span></div><div class="scene-stats"><span><small>{$t("COMPLETADAS")}</small><strong>03 <i>/ 05</i></strong></span><span><small>{$t("EN TU FLOW")}</small><strong>50 <i>min</i></strong></span></div><div class="scene-task"><span class="scene-checkbox checked">✓</span> {$t("Darle forma a una idea")} <span class="scene-priority">{$t("ALTA")}</span></div><div class="scene-task"><span class="scene-checkbox"></span> {$t("Crear algo que conecte")} <span class="scene-priority">{$t("MEDIA")}</span></div><div class="scene-task"><span class="scene-checkbox"></span> {$t("Disfrutar el proceso")} <span class="scene-priority">{$t("BAJA")}</span></div></div><div class="scene-timer"><span>{$t("UN MOMENTO PARA TI")}</span><div class="scene-timer-ring"><strong>25:00</strong><small>{$t("Estás en tu flow.")}</small></div><span class="scene-start">{$t("▶ Comenzar sesión")}</span></div></div><div class="showcase-bottom"><span>{$t("MENOS DISTRACCIONES. MÁS POSIBILIDADES.")}</span><span>SVELTEKIT + TYPESCRIPT</span></div><span class="project-view" aria-hidden="true">{$t("Ver demo")} <Icon name="arrow" size={19} /></span></div><div class="showcase-info"><div><h3>Focus Flow<span>↗</span></h3><p>{$t("Un espacio para organizarte y encontrar tu enfoque.")}</p></div><div class="showcase-meta"><span>{$t("DISEÑO & DESARROLLO")}</span><span>2026</span></div></div></a>
    <a class="showcase sprint-showcase" href="/works/pixel-sprint/" use:reveal use:projectMotion use:ambientMotion><div class="showcase-image"><div class="sprint-lines" aria-hidden="true"></div><div class="showcase-top"><span>PIXEL SPRINT™</span><span>{$t("CREATIVE PLAYGROUND / 02")}</span></div><div class="sprint-scene" aria-hidden="true"><div class="sprint-wordmark">PIXEL<br /><span>SPRINT</span><i>↗</i></div><div class="sprint-mini-board"><span></span><span></span><span></span><span></span><span class="mini-target"><Asterisk /></span><span></span><span></span><span></span><span></span></div><div class="sprint-score"><span>{$t("HIGH SCORE")}</span><strong>02450</strong><span class="sprint-score-status">{$t("YOUR NEXT LITTLE OBSESSION.")}</span></div></div><div class="showcase-bottom"><span>{$t("30 SEGUNDOS. TODOS TUS REFLEJOS.")}</span><span>{$t("PRESS PLAY →")}</span></div><span class="project-view" aria-hidden="true">{$t("Jugar")} <Icon name="arrow" size={19} /></span></div><div class="showcase-info"><div><h3>Pixel Sprint<span>↗</span></h3><p>{$t("Un experimento en reflejos, ritmo y “una partida más”.")}</p></div><div class="showcase-meta"><span>{$t("INTERACCIÓN & CREATIVE CODING")}</span><span>2026</span></div></div></a>
    <NewExperiences />
  </section>
  <div class="motion-strip" aria-hidden="true" use:ambientMotion><div>{#each [0, 1, 2, 3] as repeat}<span>{$t("BUILT WITH INTENTION")} <i><Asterisk /></i> {$t("MADE TO FEEL")} <i><Asterisk /></i> {$t("ALWAYS EXPLORING")} <i><Asterisk /></i></span>{/each}</div></div>
  <section class="portfolio-contact" id="contact" use:ambientMotion><div class="contact-inner shell"><p class="eyebrow" use:reveal>{$t("04 / EL SIGUIENTE PROYECTO PODRÍA SER EL TUYO")}</p><div class="contact-title" use:reveal><h2>{$t("Una buena idea.")}<br /><span class="serif">{$t("Un gran comienzo.")}</span></h2><span class="contact-asterisk" aria-hidden="true"><Asterisk /></span></div><div class="contact-rule"><a href={contact.whatsappUrl} target="_blank" rel="noreferrer" class="contact-orb" use:magnetic><span>{$t("Hagámoslo")}<br />{$t("realidad")}</span><Icon name="external" size={23} /></a></div><div class="contact-details" use:reveal><div><span>{$t("¿QUÉ TIENES EN MENTE?")}</span><p>{$t("Cuéntame tu idea.")}<br />{$t("Lo demás lo construimos juntos.")}</p></div><a class="contact-chip" href={contact.whatsappUrl} target="_blank" rel="noreferrer" use:magnetic>WhatsApp <Icon name="external" size={15} /></a><a class="contact-chip" href={contact.emailUrl} use:magnetic>{contact.email} <Icon name="external" size={15} /></a></div><div class="contact-signature"><span>{$t("DISEÑO, CÓDIGO & BUENA ENERGÍA.")}</span><span>Johan Aristizabal © {new Date().getFullYear()}</span></div></div></section>
</div>
